#!/bin/bash

#---------------------
#
# Post-install script
#
# Executed when the agent is just installed.
# It does:
#	- Ask Server connection infos
#	- Ask gui port
#	- Add/Start the service
#
#---------------------



SERVICE_NAME="{{name}}"
SERVICE_SHORTNAME="{{shortname}}"
CONFIG_DIRECTORY="/etc/oms/"
AGENT_CONFIG_FILE="${CONFIG_DIRECTORY}bootstrap.properties"
LOG_DIRECTORY="/var/log/oms/"
LOG_FILE="${LOG_DIRECTORY}${SERVICE_SHORTNAME}.log"



# Create log directory
[ ! -d "${LOG_DIRECTORY}" ] && mkdir -p ${LOG_DIRECTORY}
# Create OMS config directory
[ ! -d "${CONFIG_DIRECTORY}" ] && mkdir -p ${CONFIG_DIRECTORY}



#----------------------------
# Ask for Server information
#----------------------------

# Logging
echo "[Post-install] Editing agent config file..." >> ${LOG_FILE}
# Get Server infos
echo -n "serverHost = " >> ${AGENT_CONFIG_FILE}
dialog --no-cancel --title 'OMS Server' --inputbox 'Which server must the service connect to?\n\nPlease enter the hostname or ip:\n' 10 50 2>> ${AGENT_CONFIG_FILE} && clear
echo >> ${AGENT_CONFIG_FILE}
echo -n "serverPort = " >> ${AGENT_CONFIG_FILE}
dialog --no-cancel --title 'Database' --inputbox 'Which server must the service connect to?\n\nPlease enter the port number:\n' 10 50 2>> ${AGENT_CONFIG_FILE} && clear
echo >> ${AGENT_CONFIG_FILE}
echo -n "guiPort = " >> ${AGENT_CONFIG_FILE}
dialog --no-cancel --title 'GUI' --inputbox 'On which port the GUI must be available?\n\nPlease enter the port number:\n' 10 50 2>> ${AGENT_CONFIG_FILE} && clear
echo >> ${AGENT_CONFIG_FILE}
# Logging
echo "[Post-install] Bootstrap config file edited" >> ${LOG_FILE}



#-------------
# Add service
#-------------

# Add auto-start
update-rc.d ${SERVICE_NAME} defaults
# Start service
/etc/init.d/${SERVICE_NAME} start
